baseURL = "https://liuguannan98.github.io/"
languageCode = "en-us"
title = "Grant Liu"
theme = "personal-web"
copyright="© Grant Liu"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true
#publishDir = “docs”

[params.intro]
  main = "Hi, I'm Grant :wave:"
  sub = "I'm a graduate student at Cornell University"

[params.main]
  latestPublishHeader = " "

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  hideHUGOSupport = true

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/luffy.jpeg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/liuguannan98"
  linkedin = "https://www.linkedin.com/in/guannanl/"

[params.contact]
  email = "liuguannan233@gmail.com"
  text= "Contact Me" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About Me"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  title = "Projects"
  url = "/projects/"
  weight = -110

[[menu.main]]
  identifier = "misc"
  name = "Misc"
  title = "Misc section"
  url = "/misc/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true